/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Controller.BookInterface;
import Controller.ControlAccount;
import Controller.ControlBook;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quangns
 */
public class BorrowedForm extends javax.swing.JFrame implements BookInterface{
    private static String[] row;
    /**
     * Creates new form BorrowedForm
     */
    public BorrowedForm() {
        initComponents();
        test();
    }

    public void test(){
        DefaultTableModel model = (DefaultTableModel)FieldTable1.getModel();
        for (int i = model.getRowCount()-1; i >= 0; i--) {
//            System.out.println("xoa row thu "+i);
            model.removeRow(i);
        }
        
        try {
            String cid = new ControlAccount().GetCard();
            new ControlBook(this).ShowBook(cid);
        }   
        catch (Exception e) {
            System.err.println("Error: " + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtSignOut = new javax.swing.JButton();
        BtActiveCard = new javax.swing.JButton();
        BtChangePassword = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FieldTable1 = new javax.swing.JTable();
        BtSearchBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(359, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Borrowed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        BtSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        BtSignOut.setText("Sign Out");
        BtSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSignOutActionPerformed(evt);
            }
        });

        BtActiveCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Sync.png"))); // NOI18N
        BtActiveCard.setText("ActiveCard");
        BtActiveCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtActiveCardActionPerformed(evt);
            }
        });

        BtChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Wrench.png"))); // NOI18N
        BtChangePassword.setText("ChangePassword");
        BtChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtChangePasswordActionPerformed(evt);
            }
        });

        FieldTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Author", "Publisher", "Price"
            }
        ));
        jScrollPane1.setViewportView(FieldTable1);
        if (FieldTable1.getColumnModel().getColumnCount() > 0) {
            FieldTable1.getColumnModel().getColumn(0).setMinWidth(10);
            FieldTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        BtSearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Find.png"))); // NOI18N
        BtSearchBook.setText("SearchBook");
        BtSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSearchBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtSearchBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtActiveCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(BtSearchBook)
                        .addGap(18, 18, 18)
                        .addComponent(BtChangePassword)
                        .addGap(18, 18, 18)
                        .addComponent(BtActiveCard)
                        .addGap(18, 18, 18)
                        .addComponent(BtSignOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSearchBookActionPerformed
        SearchBookForm form = new SearchBookForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtSearchBookActionPerformed

    private void BtChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtChangePasswordActionPerformed
        ChangePasswordForm form = new ChangePasswordForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtChangePasswordActionPerformed

    private void BtActiveCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtActiveCardActionPerformed
        ActiveCardForm form = new ActiveCardForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtActiveCardActionPerformed

    private void BtSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSignOutActionPerformed
        SignInForm form = new SignInForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtSignOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowedForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowedForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtActiveCard;
    private javax.swing.JButton BtChangePassword;
    private javax.swing.JButton BtSearchBook;
    private javax.swing.JButton BtSignOut;
    private javax.swing.JTable FieldTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ShowBooks(String bid, String title, String author, String publisher, String price) {
        try{
            String[] rowshow = {bid, title, author, publisher, price};
            row = rowshow;
            DefaultTableModel model = (DefaultTableModel)FieldTable1.getModel();
            //model.removeRow(0);
            model.addRow(row);
        }
        catch(Exception e) {
            System.err.println("error: " + e);
        }
    }

    @Override
    public void ShowErr() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
