/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Controller.BookInterface;
import Controller.ControlBook;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quangns
 */
public class SearchBookForm extends javax.swing.JFrame implements BookInterface{
    private ControlBook controlbook;
    private static String[] row;
//    private List<Object> listdata;
    /**
     * Creates new form SearchBookForm
     */
    public SearchBookForm() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtBorrowed = new javax.swing.JButton();
        BtChangePassword = new javax.swing.JButton();
        BtActiveCard = new javax.swing.JButton();
        BtSignOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FieldTable = new javax.swing.JTable();
        TextSearch = new javax.swing.JTextField();
        BtOk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtBorrow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtBorrowed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Folder.png"))); // NOI18N
        BtBorrowed.setText("Borrowed");
        BtBorrowed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBorrowedActionPerformed(evt);
            }
        });

        BtChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Wrench.png"))); // NOI18N
        BtChangePassword.setText("Change Password");
        BtChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtChangePasswordActionPerformed(evt);
            }
        });

        BtActiveCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Sync.png"))); // NOI18N
        BtActiveCard.setText("ActiveCard");
        BtActiveCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtActiveCardActionPerformed(evt);
            }
        });

        BtSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        BtSignOut.setText("Sign out");
        BtSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSignOutActionPerformed(evt);
            }
        });

        FieldTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Author", "Publisher", "Price", "Check"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        FieldTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(FieldTable);
        if (FieldTable.getColumnModel().getColumnCount() > 0) {
            FieldTable.getColumnModel().getColumn(0).setMinWidth(10);
            FieldTable.getColumnModel().getColumn(0).setMaxWidth(30);
            FieldTable.getColumnModel().getColumn(5).setMinWidth(50);
            FieldTable.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        TextSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSearchActionPerformed(evt);
            }
        });

        BtOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Apply.png"))); // NOI18N
        BtOk.setText("OK");
        BtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtOkActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel2.setBackground(new java.awt.Color(51, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SearchBook");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        BtBorrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Load.png"))); // NOI18N
        BtBorrow.setText("Borrow");
        BtBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBorrowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtBorrowed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(BtActiveCard, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(BtSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(BtOk))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtBorrow)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtOk)
                            .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtBorrowed)
                        .addGap(18, 18, 18)
                        .addComponent(BtChangePassword)
                        .addGap(18, 18, 18)
                        .addComponent(BtActiveCard)
                        .addGap(18, 18, 18)
                        .addComponent(BtSignOut)))
                .addGap(18, 18, 18)
                .addComponent(BtBorrow)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void BtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtOkActionPerformed
        ActionPressEnter();
    }//GEN-LAST:event_BtOkActionPerformed

    private void ActionPressEnter() {
        String title = TextSearch.getText();
        // delete all row in table
        DefaultTableModel model = (DefaultTableModel)FieldTable.getModel();
        for (int i = model.getRowCount()-1; i >= 0; i--) {
//            System.out.println("xoa row thu "+i);
            model.removeRow(i);
        }
        try {
            new ControlBook(this).SearchBook(title);
        }   
        catch (Exception e) {
            System.err.println("Error: " + e);
            JOptionPane.showMessageDialog(null, "Invalid information");
        }
    }
    
    private void TextSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSearchActionPerformed
        TextSearch.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                if(e.getKeyChar()==KeyEvent.VK_ENTER) {
                    ActionPressEnter();
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                }

            @Override
            public void keyReleased(KeyEvent e) {
                }
        });
    }//GEN-LAST:event_TextSearchActionPerformed

    private void BtBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBorrowActionPerformed
        DefaultTableModel model = (DefaultTableModel)FieldTable.getModel();
        int num = model.getRowCount();
        if(num > 0) {
            for (int i = 0; i < num ; i++) {
                if((boolean) model.getValueAt(i, 5)) {
                    String st = (String) model.getValueAt(i, 0);
                    try {
                        new ControlBook(this).GetBookforBorrow(st);
                    } catch (SQLException ex) {
                        Logger.getLogger(SearchBookForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        }
    }//GEN-LAST:event_BtBorrowActionPerformed

    private void BtActiveCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtActiveCardActionPerformed
        ActiveCardForm activeform = new ActiveCardForm();
        activeform.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtActiveCardActionPerformed

    private void BtChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtChangePasswordActionPerformed
        ChangePasswordForm pwform = new ChangePasswordForm();
        pwform.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtChangePasswordActionPerformed

    private void BtBorrowedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBorrowedActionPerformed
        BorrowedForm form = new BorrowedForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtBorrowedActionPerformed

    private void BtSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSignOutActionPerformed
        SignInForm form = new SignInForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtSignOutActionPerformed
    
    
    /**
     * hien thi cac sach len bang
     * @param bid ma cua sach
     * @param title ten cua sach do
     * @param author tac gia
     * @param publisher nha xuat ban
     * @param price gia cua moi quyen sach
     */
    @Override
    public void ShowBooks(String bid, String title, String author, String publisher, String price) {
        //xoa du lieu trong bang.
        
        try{
            String[] rowshow = {bid, title, author, publisher, price};
            row = rowshow;
            DefaultTableModel model = (DefaultTableModel)FieldTable.getModel();
            //model.removeRow(0);
            model.addRow(row);
        }
        catch(Exception e) {
            System.err.println("error: " + e);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SearchBookForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtActiveCard;
    private javax.swing.JButton BtBorrow;
    private javax.swing.JButton BtBorrowed;
    private javax.swing.JButton BtChangePassword;
    private javax.swing.JButton BtOk;
    private javax.swing.JButton BtSignOut;
    private javax.swing.JTable FieldTable;
    private javax.swing.JTextField TextSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ShowErr() {
        JOptionPane.showMessageDialog(null, "Xin loi ban! Sach trong kho da het");
    }
}
